namespace Test 
{
	variadic extern def printf(byte* data) : int;

	def test()
	{
		printf("calltest");
	}

	def main() : int 
	{
		test();

		int a = 7;
		int b = 7;

		if (a == b) printf("option 1");
		else if (a != b)
		{
			printf("option2");
		}
		else printf("option 3");

		return 0;
	}
}

namespace Test.test1 {}
namespace Test.test2 {}
namespace Test.test3 {}
namespace Test.test4 {}
namespace Test.test5 {}